action: ['train', 'valid', 'test']  # one of [train, train+valid, train+test, valid, test]
seed: 0
cuda: 0
data:
  type: EFO-1  # one of ['beta', 'EFO-1']
  data_folder: 'data/FB15k-237-betae'
  cpu: 10
load:
  load_model: False
  checkpoint_path: null
  step: 0
output:
  output_path: 'original/original_ConE'  # can be null, which means it will be auto_generated
  prefix: EFO-1_train
train:
  negative_sample_size: 128  # for each positive sample
  batch_size: 512
  learning_rate: 0.00005
  steps: 300000
  log_every_steps: 100
  warm_up_steps: 150000
  evaluate_every_steps: 15000
  save_every_steps: 10000
  interested_normal_forms:
    - 'DNF+MultiIU'
  formula_id_file: 'data/FB15k-237-betae/train_formulas.csv'
evaluate:  # only used when valid/test in action
  batch_size: 1000
  print: true
  interested_normal_forms:
    - 'DNF'
    - 'DNF+MultiIU'
    - 'DeMorgan'
  formula_id_file: 'data/FB15k-237-betae/test_formulas.csv'
estimator:
  embedding: ConE # one of [Transe, box, beta, dm]
  beta:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    # evaluate_union: DM # one of [DM, DNF] after parsing it can be omitted
    gamma: 60
  box:
    entity_dim: 400
    relation_dim: 400
    offset_activation: None
    center_reg: 0.02
    gamma: 60
  dm:
    entity_dim: 2
    relation_dim: 2
    hidden_dim: 1600
    num_layers: 2
  logic:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    gamma: 0.375
    t_norm: luk
    bounded: 0
    use_att: 1
    use_gtrans: 0
  cqd:
    entity_dim: 1000 # actually 2000
    relation_dim: 1000
    norm_type: product
  NewLook:
    entity_dim: 400
    relation_dim: 400
    center_reg: 0.2
    x_reg: 0.2 # \lambda in the paper
  ConE:
    entity_dim: 800
    relation_dim: 1600
    hidden_dim: 1600
    num_layer: 2
    gamma: 30
    center_reg: 0.02
    drop: 0.1


